post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFzaWFudHVudGlqYSIsImlkIjoiNWQ5MzcwYWVkYjhiZDgyMDkwOTVmOGI4IiwiaWF0IjoxNTY5OTQzNzYwfQ.utiZDxdU1ZXI9ZwQ84jVJD08rZjvnV8P1HtMVpCTIig

{
  "title": "Otsikko",
  "author": "Joku Muu",
  "url": "http://www.teksti.com/blogi/",
  "likes": "444444"
}